import { CPUModel } from '@/app/types/cpu';

export const cpuModels: CPUModel[] = [
  {
    id: 'cpu',
    name: 'CPU Cooler Assembly',
    manufacturer: 'Generic',
    description:
      'High-performance CPU cooling solution with heat pipes and fan',
    fullModelPath: '/models/cpu_cooler.glb',
    thumbnail: '/models/cpu-parts/cpucoolertm.jpeg',
    exploreImage: '/models/cpu-parts/c00lerlab.jpeg',
    exploreVideo: '/models/cpu-parts/cpucooler1.mp4',
    parts: [
      {
        id: 'fan',
        name: 'Cooling Fan',
        description: 'High-speed fan that pushes air through the heatsink fins',
        position: { x: 0, y: 1, z: 0 },
        color: '#333333',
      },
      {
        id: 'heatsink',
        name: 'Heatsink Fins',
        description: 'Aluminum fins that dissipate heat into the air',
        position: { x: 0, y: 0.5, z: 0 },
        color: '#c0c0c0',
      },
      {
        id: 'heatpipes',
        name: 'Heat Pipes',
        description: 'Copper tubes that transfer heat from base to fins',
        position: { x: 0, y: 0, z: 0 },
        color: '#b87333',
      },
      {
        id: 'base',
        name: 'Contact Base',
        description: 'Copper base plate that makes contact with CPU',
        position: { x: 0, y: -0.5, z: 0 },
        color: '#b87333',
      },
    ],
  },
  {
  id: 'ram-module',
  name: 'RAM Module',
  manufacturer: 'Generic',
  description:
    'High-speed memory module used for temporary data storage and fast access',
  fullModelPath: '/models/ram_labels.glb', // 👈 YOUR MODEL PATH HERE
  thumbnail: '/models/cpu-parts/ramtm.jpeg',
  exploreImage: '/models/cpu-parts/ramlab.jpeg',
  exploreVideo: '/models/cpu-parts/ramvideo.mp4',
  parts: [
    {
      id: 'pcb',
      name: 'Printed Circuit Board',
      description: 'Main board that connects memory chips and circuitry',
      position: { x: 0, y: 0, z: 0 },
      color: '#1a3d2f',
    },
    {
      id: 'memory-chips',
      name: 'Memory Chips',
      description: 'Integrated circuits that store and retrieve data',
      position: { x: 0, y: 0.2, z: 0 },
      color: '#111111',
    },
    {
      id: 'heatspreader',
      name: 'Heat Spreader',
      description: 'Metal cover that dissipates heat from memory chips',
      position: { x: 0, y: 0.4, z: 0 },
      color: '#b0b0b0',
    },
    {
      id: 'gold-contacts',
      name: 'Gold Contacts',
      description: 'Conductive pins that interface with the motherboard slot',
      position: { x: 0, y: -0.5, z: 0 },
      color: '#d4af37',
    },
  ],
},
{
  id: 'gpu',
  name: 'GPU Assembly',
  manufacturer: 'Generic',
  description:
    'High-performance graphics processing unit with cooling solution and PCB',
  fullModelPath: '/models/gpu_labels.glb', // 👈 YOUR MODEL PATH HERE
  thumbnail: '/models/cpu-parts/gputm1.jpeg',
  exploreImage: '/models/cpu-parts/gpuimg.jpeg',
  exploreVideo: '/models/cpu-parts/gpuvideo.mp4',
  parts: [
    {
      id: 'gpu-chip',
      name: 'GPU Chip',
      description: 'Main graphics processor that handles rendering and computation',
      position: { x: 0, y: 0, z: 0 },
      color: '#1a1a1a',
    },
    {
      id: 'cooling-fan',
      name: 'Cooling Fan',
      description: 'High-speed fan that dissipates heat from the heatsink',
      position: { x: 0, y: 1, z: 0 },
      color: '#333333',
    },
    {
      id: 'heatsink',
      name: 'Heatsink',
      description: 'Aluminum fins that spread heat away from the GPU chip',
      position: { x: 0, y: 0.5, z: 0 },
      color: '#c0c0c0',
    },
    {
      id: 'pcb',
      name: 'Printed Circuit Board',
      description: 'Board that houses GPU chip, VRAM, and power delivery components',
      position: { x: 0, y: -0.5, z: 0 },
      color: '#006400',
    },
    {
      id: 'vram',
      name: 'Video Memory (VRAM)',
      description: 'High-speed memory modules for storing textures and frame data',
      position: { x: 0.5, y: -0.5, z: 0 },
      color: '#000080',
    },
    {
      id: 'power-connectors',
      name: 'Power Connectors',
      description: 'Connectors that supply additional power to the GPU',
      position: { x: -0.5, y: -0.5, z: 0 },
      color: '#ffcc00',
    },
    {
      id: 'io-ports',
      name: 'I/O Ports',
      description: 'HDMI, DisplayPort, and other output interfaces for monitors',
      position: { x: 1, y: -0.5, z: 0 },
      color: '#808080',
    },
  ],
},
{
  id: 'nvme-ssd',
  name: 'NVMe SSD Assembly',
  manufacturer: 'Generic',
  description:
    'High-speed solid-state drive using NVMe interface for fast data transfer',
  fullModelPath: '/models/nvmessd_labels.glb', // 👈 YOUR MODEL PATH HERE
  thumbnail: '/models/cpu-parts/nvmetm1.jpeg',
  exploreImage: '/models/cpu-parts/nvmelab.jpeg',
  exploreVideo: '/models/cpu-parts/nvmevideo.mp4',
  parts: [
    {
      id: 'controller',
      name: 'SSD Controller',
      description: 'Main chip that manages data flow between NAND and system',
      position: { x: 0, y: 0, z: 0 },
      color: '#1a1a1a',
    },
    {
      id: 'nand-flash',
      name: 'NAND Flash Memory',
      description: 'Storage modules that hold user data',
      position: { x: 0.5, y: 0, z: 0 },
      color: '#000080',
    },
    {
      id: 'dram-cache',
      name: 'DRAM Cache',
      description: 'Temporary memory for accelerating read/write operations',
      position: { x: -0.5, y: 0, z: 0 },
      color: '#ffcc00',
    },
    {
      id: 'pcb',
      name: 'Printed Circuit Board',
      description: 'Board that connects all components and provides NVMe interface',
      position: { x: 0, y: -0.5, z: 0 },
      color: '#006400',
    },
    {
      id: 'm2-connector',
      name: 'M.2 Connector',
      description: 'Interface that connects the SSD to the motherboard',
      position: { x: 1, y: -0.5, z: 0 },
      color: '#808080',
    },
  ],
},
{
  id: 'hdd',
  name: 'HDD Assembly',
  manufacturer: 'Generic',
  description:
    'Traditional hard disk drive with spinning platters and magnetic read/write heads',
  fullModelPath: '/models/hdd_labels.glb', // 👈 YOUR MODEL PATH HERE
  thumbnail: '/models/cpu-parts/hddtm1.jpeg',
  exploreImage: '/models/cpu-parts/cpu-parts.jpeg',
  exploreVideo: '/models/cpu-parts/hddvideo.mp4',
  parts: [
    {
      id: 'platters',
      name: 'Platters',
      description: 'Magnetic disks that store data in concentric tracks',
      position: { x: 0, y: 0, z: 0 },
      color: '#c0c0c0',
    },
    {
      id: 'spindle',
      name: 'Spindle Motor',
      description: 'Motor that spins the platters at high speed',
      position: { x: 0, y: -0.5, z: 0 },
      color: '#808080',
    },
    {
      id: 'actuator-arm',
      name: 'Actuator Arm',
      description: 'Arm that moves the read/write head across the platters',
      position: { x: 0.5, y: 0, z: 0 },
      color: '#333333',
    },
    {
      id: 'read-write-head',
      name: 'Read/Write Head',
      description: 'Tiny magnetic head that reads and writes data on the platters',
      position: { x: 0.5, y: 0.2, z: 0 },
      color: '#ffcc00',
    },
    {
      id: 'pcb',
      name: 'Controller PCB',
      description: 'Circuit board that manages data transfer and drive operations',
      position: { x: 0, y: -1, z: 0 },
      color: '#006400',
    },
    {
      id: 'casing',
      name: 'Drive Casing',
      description: 'Protective enclosure that houses all internal components',
      position: { x: 0, y: 0.5, z: 0 },
      color: '#1a1a1a',
    },
    {
      id: 'sata-connector',
      name: 'SATA Connector',
      description: 'Interface for connecting the HDD to the motherboard',
      position: { x: 1, y: -0.5, z: 0 },
      color: '#808080',
    },
  ],
},
{
  id: 'motherboard',
  name: 'Motherboard Assembly',
  manufacturer: 'Generic',
  description:
    'Main printed circuit board that connects and powers all PC components',
  fullModelPath: '/models/motherboard__labels.glb', // 👈 YOUR MODEL PATH HERE
  thumbnail: '/models/cpu-parts/motherboardtm1.jpeg',
  exploreImage: '/models/cpu-parts/motherboardlab.jpeg',
  exploreVideo: '/models/cpu-parts/motherboardvideo.mp4',
  parts: [
    {
      id: 'cpu-socket',
      name: 'CPU Socket',
      description: 'Slot where the processor is installed',
      position: { x: 0, y: 0, z: 0 },
      color: '#808080',
    },
    {
      id: 'ram-slots',
      name: 'RAM Slots',
      description: 'DIMM slots for installing system memory modules',
      position: { x: 0.5, y: 0, z: 0 },
      color: '#000080',
    },
    {
      id: 'pci-express-slots',
      name: 'PCI Express Slots',
      description: 'Expansion slots for GPU, NVMe adapters, and other cards',
      position: { x: -0.5, y: 0, z: 0 },
      color: '#333333',
    },
    {
      id: 'chipset',
      name: 'Chipset',
      description: 'Controller hub that manages communication between CPU, RAM, and peripherals',
      position: { x: 0, y: -0.5, z: 0 },
      color: '#1a1a1a',
    },
    {
      id: 'storage-connectors',
      name: 'Storage Connectors',
      description: 'SATA and M.2 connectors for SSDs and HDDs',
      position: { x: 0.5, y: -0.5, z: 0 },
      color: '#c0c0c0',
    },
    {
      id: 'power-connectors',
      name: 'Power Connectors',
      description: 'ATX and CPU power connectors that supply electricity to the board',
      position: { x: -0.5, y: -0.5, z: 0 },
      color: '#ffcc00',
    },
    {
      id: 'io-ports',
      name: 'Rear I/O Ports',
      description: 'USB, HDMI, Ethernet, and audio ports for external connectivity',
      position: { x: 1, y: 0, z: 0 },
      color: '#006400',
    },
    {
      id: 'vrm',
      name: 'Voltage Regulator Modules (VRM)',
      description: 'Power delivery components that regulate voltage for the CPU',
      position: { x: -1, y: 0, z: 0 },
      color: '#b87333',
    },
  ],
},
{
  id: 'monitor',
  name: 'Monitor Assembly',
  manufacturer: 'Generic',
  description:
    'Display device for visual output, featuring screen panel, housing, and connectivity ports',
  fullModelPath: '/models/monitor_labels.glb', // 👈 YOUR MODEL PATH HERE
  thumbnail: '/models/cpu-parts/monitertm.jpeg',
  exploreImage: '/models/cpu-parts/monitorlab.jpeg',
  exploreVideo: '/models/cpu-parts/monitervideo.mp4',
  parts: [
    {
      id: 'screen-panel',
      name: 'Screen Panel',
      description: 'LCD/LED panel that displays images and video',
      position: { x: 0, y: 0, z: 0 },
      color: '#000000',
    },
    {
      id: 'bezel',
      name: 'Bezel',
      description: 'Outer frame surrounding the screen panel',
      position: { x: 0, y: 0.1, z: 0 },
      color: '#1a1a1a',
    },
    {
      id: 'stand',
      name: 'Stand',
      description: 'Support structure that holds the monitor upright',
      position: { x: 0, y: -0.5, z: 0 },
      color: '#808080',
    },
    {
      id: 'back-cover',
      name: 'Back Cover',
      description: 'Protective casing that houses internal components',
      position: { x: 0, y: -0.2, z: -0.1 },
      color: '#333333',
    },
    {
      id: 'power-supply',
      name: 'Internal Power Supply',
      description: 'Circuitry that provides power to the monitor',
      position: { x: -0.5, y: -0.2, z: 0 },
      color: '#ffcc00',
    },
    {
      id: 'io-ports',
      name: 'I/O Ports',
      description: 'HDMI, DisplayPort, USB, and other connectors for input/output',
      position: { x: 0.5, y: -0.2, z: 0 },
      color: '#006400',
    },
    {
      id: 'buttons',
      name: 'Control Buttons',
      description: 'Physical buttons for power and menu navigation',
      position: { x: 1, y: -0.3, z: 0 },
      color: '#c0c0c0',
    },
  ],
},
{
  id: 'processor',
  name: 'Processor Assembly',
  manufacturer: 'Generic',
  description:
    'Central Processing Unit (CPU) responsible for executing instructions and managing system operations',
  fullModelPath: '/models/processer_labels.glb', // 👈 YOUR MODEL PATH HERE
  thumbnail: '/models/cpu-parts/processertm.jpeg',
  exploreImage: '/models/cpu-parts/processerlab.jpeg',
  exploreVideo: '/models/cpu-parts/cpu-explore.mp4',
  parts: [
    {
      id: 'cpu-die',
      name: 'CPU Die',
      description: 'Silicon chip containing billions of transistors for computation',
      position: { x: 0, y: 0, z: 0 },
      color: '#1a1a1a',
    },
    {
      id: 'integrated-heat-spreader',
      name: 'Integrated Heat Spreader (IHS)',
      description: 'Metal lid that protects the die and transfers heat to the cooler',
      position: { x: 0, y: 0.2, z: 0 },
      color: '#c0c0c0',
    },
    {
      id: 'substrate',
      name: 'Substrate',
      description: 'Green PCB base that connects the CPU die to motherboard socket',
      position: { x: 0, y: -0.2, z: 0 },
      color: '#006400',
    },
    {
      id: 'pins',
      name: 'Pins / Contact Pads',
      description: 'Electrical contacts that interface with the motherboard socket',
      position: { x: 0, y: -0.5, z: 0 },
      color: '#ffcc00',
    },
    {
      id: 'cache',
      name: 'On-chip Cache',
      description: 'High-speed memory integrated into the CPU for quick data access',
      position: { x: 0.5, y: 0, z: 0 },
      color: '#000080',
    },
    {
      id: 'cores',
      name: 'CPU Cores',
      description: 'Independent processing units within the CPU die',
      position: { x: -0.5, y: 0, z: 0 },
      color: '#b87333',
    },
  ],
},
{
  id: 'psu',
  name: 'Power Supply Unit Assembly',
  manufacturer: 'Generic',
  description:
    'Component that converts AC power from the wall into regulated DC power for the PC',
  fullModelPath: '/models/psu_labels.glb', // 👈 YOUR MODEL PATH HERE
  thumbnail: '/models/cpu-parts/psutm.jpeg',
  exploreImage: '/models/cpu-parts/psulab.jpeg',
  exploreVideo: '/models/cpu-parts/psuvideo.mp4',
  parts: [
    {
      id: 'housing',
      name: 'PSU Housing',
      description: 'Metal casing that encloses all internal components',
      position: { x: 0, y: 0, z: 0 },
      color: '#1a1a1a',
    },
    {
      id: 'fan',
      name: 'Cooling Fan',
      description: 'Fan that cools internal PSU components during operation',
      position: { x: 0, y: 0.5, z: 0 },
      color: '#333333',
    },
    {
      id: 'transformer',
      name: 'Transformer',
      description: 'Converts incoming AC voltage to usable levels',
      position: { x: -0.5, y: 0, z: 0 },
      color: '#b87333',
    },
    {
      id: 'capacitors',
      name: 'Capacitors',
      description: 'Stabilize and filter DC output power',
      position: { x: 0.5, y: 0, z: 0 },
      color: '#ffcc00',
    },
    {
      id: 'pcb',
      name: 'Controller PCB',
      description: 'Circuit board that manages voltage regulation and safety features',
      position: { x: 0, y: -0.5, z: 0 },
      color: '#006400',
    },
    {
      id: 'power-input',
      name: 'AC Power Input',
      description: 'Connector for power cable from wall outlet',
      position: { x: -1, y: -0.5, z: 0 },
      color: '#808080',
    },
    {
      id: 'power-output',
      name: 'DC Output Connectors',
      description: 'Cables that deliver power to motherboard, GPU, and storage devices',
      position: { x: 1, y: -0.5, z: 0 },
      color: '#000080',
    },
  ],
},
{
  id: 'webcam',
  name: 'Webcam Assembly',
  manufacturer: 'Generic',
  description:
    'Compact camera device for capturing video and images, typically used for video calls and streaming',
  fullModelPath: '/models/webcamera_labels.glb', // 👈 YOUR MODEL PATH HERE
  thumbnail: '/models/cpu-parts/webcamtm.jpeg',
  exploreImage: '/models/cpu-parts/weblab.jpeg',
  exploreVideo: '/models/cpu-parts/webcamvideo.mp4',
  parts: [
    {
      id: 'lens',
      name: 'Camera Lens',
      description: 'Optical lens that focuses light onto the image sensor',
      position: { x: 0, y: 0, z: 0 },
      color: '#000000',
    },
    {
      id: 'image-sensor',
      name: 'Image Sensor',
      description: 'Electronic sensor that converts light into digital signals',
      position: { x: 0, y: -0.2, z: 0 },
      color: '#1a1a1a',
    },
    {
      id: 'microphone',
      name: 'Built-in Microphone',
      description: 'Captures audio during video calls or recordings',
      position: { x: 0.5, y: -0.2, z: 0 },
      color: '#333333',
    },
    {
      id: 'pcb',
      name: 'Controller PCB',
      description: 'Circuit board that manages image processing and connectivity',
      position: { x: -0.5, y: -0.2, z: 0 },
      color: '#006400',
    },
    {
      id: 'casing',
      name: 'Webcam Housing',
      description: 'Protective casing that encloses lens, sensor, and electronics',
      position: { x: 0, y: 0.2, z: 0 },
      color: '#808080',
    },
    {
      id: 'usb-connector',
      name: 'USB Connector',
      description: 'Interface for connecting the webcam to the computer',
      position: { x: 1, y: -0.5, z: 0 },
      color: '#000080',
    },
    {
      id: 'mount',
      name: 'Mount/Stand',
      description: 'Adjustable mount or clip for attaching the webcam to a monitor or surface',
      position: { x: 0, y: -0.8, z: 0 },
      color: '#c0c0c0',
    },
    {
      id: 'indicator-light',
      name: 'Indicator Light',
      description: 'LED light that shows when the webcam is active',
      position: { x: -1, y: -0.3, z: 0 },
      color: '#ffcc00',
    },
  ],
},
{
  id: 'keyboard',
  name: 'Keyboard Assembly',
  manufacturer: 'Generic',
  description:
    'Input device with keys for typing, gaming, and system control',
  fullModelPath: '/models/keyboard_labels.glb', // 👈 YOUR MODEL PATH HERE
  thumbnail: '/models/cpu-parts/keyboardtm.jpeg',
  exploreImage: '/models/cpu-parts/keyboardlab.jpeg',
  exploreVideo: '/models/cpu-parts/keyboardvideo.mp4',
  parts: [
    {
      id: 'keycaps',
      name: 'Keycaps',
      description: 'Plastic tops of the keys that users press',
      position: { x: 0, y: 0, z: 0 },
      color: '#c0c0c0',
    },
    {
      id: 'switches',
      name: 'Switches',
      description: 'Mechanical or membrane switches beneath keycaps that register input',
      position: { x: 0, y: -0.2, z: 0 },
      color: '#333333',
    },
    {
      id: 'pcb',
      name: 'Keyboard PCB',
      description: 'Circuit board that detects key presses and sends signals to the computer',
      position: { x: 0, y: -0.5, z: 0 },
      color: '#006400',
    },
    {
      id: 'frame',
      name: 'Keyboard Frame',
      description: 'Outer casing that holds all components together',
      position: { x: 0, y: 0.2, z: 0 },
      color: '#1a1a1a',
    },
    {
      id: 'stabilizers',
      name: 'Stabilizers',
      description: 'Support mechanisms for larger keys like spacebar and enter',
      position: { x: 0.5, y: -0.2, z: 0 },
      color: '#808080',
    },
    {
      id: 'backlight',
      name: 'Backlight LEDs',
      description: 'LEDs that illuminate keys for visibility and aesthetics',
      position: { x: -0.5, y: -0.2, z: 0 },
      color: '#ffcc00',
    },
    {
      id: 'usb-connector',
      name: 'USB Connector',
      description: 'Cable or wireless dongle that connects the keyboard to the computer',
      position: { x: 1, y: -0.5, z: 0 },
      color: '#000080',
    },
  ],
},
{
  id: 'mouse',
  name: 'Mouse Assembly', 
  manufacturer: 'Generic',
  description:
    'Handheld pointing device used to control cursor movement and interact with the computer',
  fullModelPath: '/models/mouse_labels.glb', // 👈 YOUR MODEL PATH HERE
  thumbnail: '/models/cpu-parts/mousetm.jpeg',
  exploreImage: '/models/cpu-parts/mouselab.jpeg',
  exploreVideo: '/models/cpu-parts/mousevideo.mp4',
  parts: [
    {
      id: 'left-button',
      name: 'Left Button',
      description: 'Primary button for selecting and interacting with items',
      position: { x: -0.2, y: 0, z: 0 },
      color: '#c0c0c0',
    },
    {
      id: 'right-button',
      name: 'Right Button',
      description: 'Secondary button for context menus and additional actions',
      position: { x: 0.2, y: 0, z: 0 },
      color: '#c0c0c0',
    },
    {
      id: 'scroll-wheel',
      name: 'Scroll Wheel',
      description: 'Wheel for scrolling through documents and web pages',
      position: { x: 0, y: 0.1, z: 0 },
      color: '#808080',
    },
    {
      id: 'sensor',
      name: 'Optical/Laser Sensor',
      description: 'Tracks movement across surfaces and translates it into cursor motion',
      position: { x: 0, y: -0.5, z: 0 },
      color: '#000000',
    },
    {
      id: 'pcb',
      name: 'Controller PCB',
      description: 'Circuit board that processes input signals from buttons and sensor',
      position: { x: 0, y: -0.3, z: 0 },
      color: '#006400',
    },
    {
      id: 'casing',
      name: 'Mouse Housing',
      description: 'Plastic shell that encloses all internal components',
      position: { x: 0, y: 0.2, z: 0 },
      color: '#1a1a1a',
    },
    {
      id: 'usb-connector',
      name: 'USB Connector / Wireless Receiver',
      description: 'Interface for connecting the mouse to the computer',
      position: { x: 1, y: -0.5, z: 0 },
      color: '#000080',
    },
    {
      id: 'dpi-button',
      name: 'DPI Adjustment Button',
      description: 'Button to change sensitivity levels for cursor speed',
      position: { x: -0.5, y: 0.1, z: 0 },
      color: '#ffcc00',
    },
  ],
},
  // You can add more models here later
];

export function getCPUModel(id: string): CPUModel | undefined {
  return cpuModels.find((model) => model.id === id);
}

export function getAllCPUModels(): CPUModel[] {
  return cpuModels;
}